// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WebsiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void website() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".login_credentials_wrap-inner")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector(".login_credentials_wrap-inner")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector(".login_credentials_wrap-inner")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-password\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"logout-sidebar-link\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("locked_out_user");
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-password\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-button\"]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-password\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".login_wrapper-inner")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-button\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-button\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector(".form_group:nth-child(2) path")).click();
    driver.findElement(By.cssSelector(".form_group:nth-child(1) path")).click();
    driver.findElement(By.cssSelector(".form_group:nth-child(1) > .svg-inline--fa")).click();
    driver.findElement(By.cssSelector(".form_group:nth-child(1) > .svg-inline--fa")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".form_group:nth-child(1) > .svg-inline--fa"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".fa-times")).click();
    driver.findElement(By.cssSelector(".login_wrapper-inner")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("problem_user");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"logout-sidebar-link\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("performance_glitch_user");
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-password\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"logout-sidebar-link\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("error_user");
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-password\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-button\"]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"logout-sidebar-link\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("visual_user");
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-password\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"logout-sidebar-link\"]")).click();
  }
}
